# Generated by Django 4.2.5 on 2023-09-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_shop', '0002_client_rename_desription_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(related_name='order', to='my_shop.product'),
        ),
    ]
